### PR TITLE
Hide Blizzard Time Indicator

### PR DESCRIPTION
**Pull request by draknyte1**
Not sure how localization is done for this project, however I placed this into  `lang/enUS.lua` and it worked fine though.

`L["MinMapHideTimeIndicator"] = "Hide Time Indicator"`

Let me know if I missed anything. 😄 

image

### CODE REVIEW

**Comment by Wutname1** [comment]
Can you change localization to:
`L["Hide Time Indicator"] = true`

I don't see any code to hide the indicator.

**Comment by draknyte1** [comment]
> Can you change localization to:
> L["Hide Time Indicator"] = true

Not sure where you'd like this done, feel free to edit the files in the PR or point me to the line.

**Comment by Wutname1** [comment]
On line 660 swap L['MinMapHideTimeIndicator'] to L["Hide Time Indicator"]. I have already added it to the localization system.

**Comment by Wutname1** [comment]
> feel free to edit the files in the PR

FYI I cant as the branch being merged is in your repo not a repo i have push permissions to. I would have to merge it then fix it after the fact.

**Comment by draknyte1** [comment]
> FYI I cant
GitHub provides the option when creating the PR to allow changes by the repo owner. Just click the files changed tab, then the ..., then hit edit. Should work, if not I’ll make the change after work today. :)

**Pull request merged**
